export default {
  extends: ['@commitlint/config-conventional'],
  rules: {
    'type-enum': [
      2,
      'always',
      [
        'codestyle',
        'perf',
        'prune',
        'bugfix',
        'hotfix',
        'feature',
        'feat',
        'docs',
        'deploy',
        'ui',
        'init',
        'tests',
        'security',
        'tags',
        'lint',
        'wip',
        'fixci',
        'downgrade',
        'upgrade',
        'depver',
        'ci',
        'analytics',
        'refactor',
        'depadd',
        'deprm',
        'config',
        'devscripts',
        'i18n',
        'typo',
        'flaky',
        'revert',
        'merge',
        'binary',
        'contract',
        'relocate',
        'license',
        'breaking',
        'assets',
        'a11y',
        'comment',
        'gibberfish',
        'text',
        'db',
        'addlogs',
        'rmlogs',
        'contrib',
        'ux',
        'arch',
        'responsive',
        'mock',
        'joke',
        'gitignore',
        'snapshots',
        'poc',
        'seo',
        'types',
        'seed',
        'flags',
        'detect',
        'animation',
        'deprecate',
        'auth',
        'fix',
        'explore',
        'clean',
        'fall',
        'docker',
      ],
    ],
    'subject-case': [2, 'always', ['sentence-case', 'lower-case']],
    'header-max-length': [2, 'always', 200],
    'type-case': [2, 'always', 'lower-case'],
    'type-empty': [2, 'never'],
    'subject-empty': [2, 'never'],
    'subject-full-stop': [2, 'always', '.'],
    'body-leading-blank': [2, 'always'],
    'footer-leading-blank': [1, 'always'],
  },
  parserPreset: {
    parserOpts: {
      headerPattern: /^(:\w*:)?\s?(\w*)(?:\((.*)\))?!?:\s(.*)$/,
      headerCorrespondence: ['emoji', 'type', 'scope', 'subject'],
    },
  },
};
