export enum SecurityLevel {
  SAFE_METHOD_AND_NO_SECRET = 'SAFE_METHOD_AND_NO_SECRET',
  PROTECTED_METHOD_NO_SECRET_FOUND = 'NO_SECRET_FOR_PROTECTED_METHOD',
  PROTECTED_METHOD_AND_FOUND_SECRET = 'CHECK_TOKEN_VALIDITY',
  OK = 'OK',
}
